### PR TITLE
Add 2nd "God"

### PR DESCRIPTION
**Pull request by iangcarroll**
Will help with network reliability. Also added a comment explaining each entry.

### CODE REVIEW

**Comment by iangcarroll** [comment]
@max00355 If you want me to add you to the notification system for the monitor then PM me on Inqre.

**Comment by f-prime** [comment]
What do you mean?

**Comment by iangcarroll** [comment]
@Max00355 You added it to the config...

**Comment by f-prime** [comment]
Ohhh, I read that wrong, sorry.

**Pull request closed without merging**
